config/routes.rb
Rails.application.routes.draw do
  resources :events

  root 'pages#home'

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, presence: true
	validates :startdate, presence: true
	validates :enddate, presence: true

	CATEGORIES = ['Conference', 'Seminar', 'Hackaton', 'Meetup']

	scope :active, -> { where("enddate < ?", Time.now) }
	scope :finished, -> { where("enddate > ?", Time.now) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		
		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	def index
		@events = Event.all
	end

	def edit
		@event = Event.find(params[:id])
	end	

	def update
		@event = Event.find(params[:id])
		
		if @event.update(event_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		
		redirect_to events_path
	end


	private

  def event_params
    params.require(:event).permit(:title, :description, :link, :startdate, :enddate, :category, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
	end

	def contact
	end

	def about
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title, options={})
  		content_for(:title, page_title.to_s)
	end

	def nav_link(link_text, link_path)
  	class_name = current_page?(link_path) ? 'active' : ''

  	content_tag(:li, :class => class_name) do
    	link_to link_text, link_path
  	end
	end

end

app/helpers/events_helper.rb
module EventsHelper

	def color_category(category)
		case category
		when 'Conference'
			content_tag(:span, :class => 'label') do
				category
			end
		when 'Seminar'
			content_tag(:span, :class => 'success label') do
				category
			end
		when 'Hackaton'
			content_tag(:span, :class => 'alert label') do
				category
			end
		when 'Meetup'
			content_tag(:span, :class => 'warning label') do
				category
			end
		else
			content_tag(:span, :class => 'secondary label') do
				category
			end
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_event.html.erb
<div class="row">
	<div class="large-4 columns">
		<h5><%= link_to event.title, event_path(event) %></h5>
	</div>
	<div class="large-2 columns">
		<%= color_category(event.category) %>
	</div>
  <div class="large-2 columns">
		<p><%= event.startdate.strftime("%d/%m/%Y") %></p>
	</div>
	<div class="large-2 columns">
		<p><%= event.address %></p>
	</div>
	<div class="large-2 columns">
		<%= link_to "Show", event_path(event) %>
		<%= link_to "Edit", edit_event_path(event) %>
		<%= link_to "Delete", event_path(event),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </div>      
</div>

<hr />          

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.input :title %>
  </p>
 
  <p>
    <%= f.input :description, :cols => "30", :rows => "10" %>
  </p>
 
  <p>
    <%= f.input :link %>
  </p>

  <p>
    <%= f.input :category, collection: Event::CATEGORIES, selected: Event::CATEGORIES[0] %>
  </p>
    
  <p>
    <%= f.input :address, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Start typing a place...' %>
  </p>

  <p>
    <%= f.input :startdate, :default => Time.now %>
  </p>

  <p>
    <%= f.input :enddate, :default => Time.now  %>
  </p>  

  <p>
    <%= f.button :submit, "Submit", class: "button"  %>
  </p>
 
<% end %>
 
<%= link_to 'Back', events_path %>

app/views/events/edit.html.erb
<% title "Edit event" %>

<div class="row">

	<div class="large-12 columns">
		<h1>Edit event</h1>

		<%= render 'form' %>
		
		</div>

</div>

app/views/events/index.html.erb
<% title "All events" %>

<div class="large-12 columns">
	
	<h1>All events</h1> 

	<% @events.each do |event| %>
	    <%= render partial: 'event', locals: {event: event} %>
	  <% end %>

	<p>	<%= link_to "Add new event", new_event_path %></p>

</div>

app/views/events/new.html.erb
<% title "New event" %>

<div class="row">

	<div class="large-12 columns">
		<h1>New event</h1>

		<%= render 'form' %>
	</div>

</div>

app/views/events/show.html.erb
<% title @event.title %>

<div class="row">
	<div class="large-9 columns">
		
		<h2><%= @event.title %></h2>
		<h4>Starts: <%= raw @event.startdate.strftime("%d/%m/%Y at %H:%M") %></h4> 
		<h4>Ends: <%= raw @event.enddate.strftime("%d/%m/%Y at %H:%M") %></h4>
		<p><%= raw @event.description %></p>
		<p><%= raw @event.link %></p>
		<p><%= raw @event.address %></p>
		<p><%= raw color_category(@event.category) %></p>

		<%= link_to "Edit", edit_event_path(@event) %>
		<%= link_to "Delete", event_path(@event),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>

		<p><%= link_to 'Back', events_path %></p>
	  <p>	<%= link_to "Add new event", new_event_path %></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "It events in Europe and Prague" %></title>

    <script type="text/javascript" src="https://maps-api-ssl.google.com/maps/api/js?sensor=false"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
 
  </head>

  <body>
  
  <div class="row">

    <nav class="top-bar" data-topbar role="navigation">
    
      <section class="top-bar-section">
        <ul class="left">
          <li><%= nav_link('All events', events_path) %></li>
        </ul>
        <ul class="right">
          <li><%= nav_link('About', about_path) %></li>
          <li><%= nav_link('Contact', contact_path) %></li>
        </ul>
      </section>
    </nav>  
  </div>

  <div class="row">  
    <%= yield %>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<% title "About page" %>

<div class='row'>
	
</div>

app/views/pages/contact.html.erb
<% title "Contact page" %>

<div class='row'>
	
</div>

app/views/pages/home.html.erb
<% title "Home page" %>

<div class='row'>
	
</div>